modLoader="javafml"
loaderVersion="[36,)"
license="LGPL"
[[mods]]
modId="soulary"
version="${file.jarVersion}"
displayName="Soulary"
authors="Hunkarada"
description='''
Soulary

Special thanks to: ConnorTron110, Cy4's Modding Community, The Forge Project community, MMD.
'''
[[dependencies.Soulary]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.Soulary]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2)"
   ordering="NONE"
   side="BOTH"
