modLoader="javafml"
loaderVersion="[36,)"
license="LGPL"
[[mods]]
modId="soulary"
version="${file.jarVersion}"
displayName="Soulary"
authors="Hunkarada"
description='''
Soulary
'''
[[dependencies.Soulary]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.Soulary]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
